第9回課題提出
Daisuke943/RaiseTech_Java_202207 pull request #10
Opened 2022-10-08 12:12 UTC by Daisuke943

第９回課題のRead処理が実装出来ましたので、提出します。

`localhost:8080/names`
にアクセスすると、namesテーブルに登録されている名前をレスポンスとして返します。

`localhost:8080/movies?published_year=2000`
にアクセスすると、moviesテーブルに登録されている映画の中から、
2000年に公開された映画をレスポンスとして返します。

実行結果とテーブル定義は、README.mdに記載しています。

レビューをお願いします。

2022-10-09 01:08 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/resources/application.properties
> +spring.datasource.username=user
秘匿情報は環境変数隠蔽するようにしましょう！
GitHub上にこういう情報を生で載せると完全に削除するのに結構手間がかかります！

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/MovieResponse.java
> +        this.id = movie.getId();
これはフィールドが空の時にどうなります？？

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/MovieResponse.java
> +@Data
@Dataは内部的にsetter/getter共に生成されるため、個人的には不用意にsetterを生成するのは良くないと考えている派なので@Dataを使用するのはあまり良くないかなと思っています！
@Setter @Getterアノテーションを各フィールドに不要することも可能ですのでそちらで対応するかrecordクラスを使うかが良いかなと思います！

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/repository/NameMapper.java
> +    List<Movie> findByYear(int year);
ここはOptionalでラップするのが良いですね！

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/service/NameService.java
> +    List<Movie> findByYear(int year) throws Exception;
ヌルポ対策で例外処理しているんですかね？？
Optionalでラップするのが良いと言うことと、Exceprionではなく、予想される例外クラスをthrowするようにするのが良いと思います！

2022-10-09 01:08 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    public List<MovieResponse> getMovies(@RequestParam(name = "published_year") int year) throws Exception {
これは例外がthrowされた時の処理をしていないと思うので例外はcatchしてしかるべきをするようにしましょう！

2022-10-12 06:23 UTC, Daisuke943 commented on src/main/resources/application.properties
> +spring.datasource.username=user
@YudaiNoda3576 
秘匿情報を環境変数隠蔽出来ました。

Macのzshシェルなので、`.zshrcファイル`に環境変数を定義して、
`source ~/.zshrc`コマンドで環境変数を反映しました。
`application.properties`には、

```
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
```
のように設定しました。動作確認も問題なかったです。

2022-10-12 13:41 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/MovieResponse.java
> +        this.id = movie.getId();
フィールドが空になるように、リスエストを送ってみました。
特にエラーになることもなく、空のJSONが返ってきます。
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/47516167/195357961-401b099a-8d90-4276-818d-092108429b86.png">

2022-10-12 13:51 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/MovieResponse.java
> +@Data
@DaTaの代わりに@Getterをクラスに付与して、不用意にsetterを生成
しないようにしました。
```
@Getter
public class MovieResponse {
```

2022-10-14 16:03 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/repository/NameMapper.java
> +    List<Movie> findByYear(int year);
Optionalでラップしました。
しかし、リクエストを送ってみると、
```
java.lang.reflect.InaccessibleObjectException: Unable to make private java.util.Optional(java.lang.Object) accessible: module java.base does not "opens java.util" to unnamed module
```
というエラーが発生してしまいます。

2022-10-14 16:05 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/service/NameService.java
> +    List<Movie> findByYear(int year) throws Exception;
はい、ヌルポ対策で例外処理しています。
予想される例外クラスをthrowするようにしました。

2022-10-14 16:06 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    public List<MovieResponse> getMovies(@RequestParam(name = "published_year") int year) throws Exception {
例外をcatch出来るよう、try-catchを実装しました。

2022-10-15 04:00 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/repository/NameMapper.java
> +    List<Movie> findByYear(int year);
@YudaiNoda3576 
こちらのサイトに、
https://stackoverflow.com/questions/49808600/how-it-get-return-optionallistvo-from-mybatis
Optionalを使う場合はDBから結果が一つか、値が得られない場合にのみに使用すると書いています。
検索結果がないようにリクエストを送ってみたのですが、nullになることはなく、ただ空のListがjsonで
返ってきただけでした。
今回の場合はListをOptionalでラップするのは、不要ではないでしょうか？

2022-10-15 07:08 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/repository/NameMapper.java
> +    List<Movie> findByYear(int year);
@YudaiNoda3576 
Optionalを無くして、Listが空だった場合の処理を実装しました。

MovieResponseにエラーメッセージ用のフィールドを用意して、
Listが空だった場合はエラーメッセージをセットして、レスポンスを返すようにしています。
ちょっと、自信がないので、レビューをお願いします。

リストが空になるようにリクエストを送った際のレスポンスは以下のようになります。
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/47516167/195974002-2c69df51-e848-4a12-aa74-73e26a222ebf.png">

2022-10-15 20:38 UTC, YudaiNoda3576 approved these changes
コメントしています！

2022-10-15 20:38 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/MovieResponse.java
> +        this.id = movie.getId();
この挙動は想定されている仕様に沿っているでしょうか？？

2022-10-15 20:38 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        NameResponse nameResponse = new NameResponse();
👍🏻

2022-10-15 20:38 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
>              movieResponseList.add(movieResponse);
movieResponseListを設定してしまうとレスポンスボディにMovieListのid: 0, name: nullなども含まれてしまうと思うのですが、ここは単純に
```
{
  "messages": "映画が見つかりませんでした"
}
```
という結果が返るようにしたいですね！

2022-10-15 20:38 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/service/NameServiceImpl.java
>              throw new NullPointerException();
実際の値はnullではないのに`NullPointerException` をthrowするのは違和感があるような🤔
ControllerクラスでListが空の時はエラーメッセージを返すでも良いように思いましたがどうでしょう？？

2022-10-15 20:39 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/repository/NameMapper.java
> +    List<Movie> findByYear(int year);
下記で指摘しているため、下記の指摘箇所で引き続きやりとりしましょう！
この度は私の知識不足でご迷惑お掛けしました！🙇

2022-10-16 14:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        NameResponse nameResponse = new NameResponse();
仕様を想定していなかったのです。
この場合はどのような挙動であれば、想定されている仕様に
なっているでしょうか？

2022-10-16 15:40 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
>              movieResponseList.add(movieResponse);
対応方法が分からないのですが、ヒントを貰えないでしょうか。

2022-10-16 15:42 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/service/NameServiceImpl.java
>              throw new NullPointerException();
確かに、nullではないのに、`NullPointerException`をthrowするのは違和感があるので、
ControllerクラスでListが空の時は対応するように実装しました。
エラーメッセージを上手く返す方法はまだ模索中です。

2022-10-17 09:23 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        NameResponse nameResponse = new NameResponse();
仕様については酒井さんにお任せするのでここはこういう仕様ならば大丈夫です！
が、他のレスポンスではmovieが空の場合はメッセージを返却しているのでそこは統一した方が良いかなと思います！

2022-10-17 09:24 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
>              movieResponseList.add(movieResponse);
`ResponseEntity`クラスを使用すると良いかと思います！

2022-10-17 15:13 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
>              movieResponseList.add(movieResponse);
エラーメッセージ用のクラスを作成して、Listが空の時はそのクラスにメッセージをセットして、
返そうと考えましたが、戻り値の型と違うのでエラーになってしまいます。

2022-10-18 14:59 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(movieResponseList);
Listが空の場合は
```
{
  "message": "映画が見つかりませんでした"
}
```
とエラーメッセージをレスポンスとして返すように修正しました。

2022-10-18 15:00 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
>              movieResponseList.add(movieResponse);
以下にコメントしています。

2022-10-18 21:49 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-10-18 21:49 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(movieResponseList);
` return ResponseEntity.status(HttpStatus.CREATED).body(movieResponseList);`

この部分はHttpStatusがCREATEDだとステータスコードが201になると思うんですが、正しいでしょうか？

また、実行結果のスクショも一緒に共有頂けますと幸いです！

2022-10-19 15:05 UTC, Daisuke943 commented
ステータスコード201はリクエストは成功し、その結果新たなリソースが作成されたことを示されるものだったので、誤りでした。

この場合はステータスコード200が正しかったです。
`HttpStatus.OK`として、ステータスコードが200になるように修正しました。

以下が実行結果です。

映画が見つかった場合
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/47516167/196727314-dcd428b6-47b6-4cee-85da-a837bfdf670a.png">

映画が見つからなかった場合
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/47516167/196726917-472b8d63-4774-4db7-ae09-9f04751be78d.png">

2022-10-19 20:29 UTC, YudaiNoda3576 commented
![LGTM](https://image.lgtmoon.dev/184841)

2022-10-20 14:02 UTC, merged