第10回課題提出
Daisuke943/RaiseTech_Java_202207 pull request #12
Opened 2022-10-29 14:39 UTC by Daisuke943

2022-10-30 12:50 UTC, yoshi-koyama commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    @Setter
idだけsetterありにせずともformであればclassにつければいいのでは？と思いました。

2022-10-30 12:50 UTC, yoshi-koyama commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +import net.raisetech.SpringBootSample.form.CreateForm;
このPRと直接関係ないですが、`.DS_Store`は`.gitignore`にいれておきましょっか。
https://github.com/Daisuke943/RaiseTech_Java_202207/blob/Task10/.DS_Store

2022-10-30 12:50 UTC, yoshi-koyama commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        } catch (NotFoundException e) {
![badge](https://img.shields.io/badge/review-imo-orange.svg)
例外処理はExceptionHandler使って共通化するとなお良いかと思います。

2022-10-30 12:51 UTC, YudaiNoda3576 requested changes
コメントしています！
実行結果のスクリーンショットの共有もお願いします🙏

2022-10-30 12:51 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        form.setId(id);
`updateForm` と `createForm` って使い分ける必要ありますかね🤔

2022-10-30 12:51 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    private int id;
これは`id` 項目がクライアントサイドから渡ってくることを想定されていますか？？
`PathVariable` を使われてると思うので、クライアントが入力する情報ではないような気がしているのですが、バリデーションは必要でしょうか？

2022-10-30 12:51 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
>      @Size(max = 19)
すみません、ここの仕様って20文字より少ないでしたっけ？
20文字以下じゃなかったでしたっけ？？

2022-10-30 12:56 UTC, yoshi-koyama commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        form.setId(id);
ここは多分教材どおりに作ってもらっていると思うのですが、一考の余地ありですね。
酒井さんの意見が聞きたい。

2022-11-01 15:29 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    @Setter
@yoshi-koyama 
formであれば、getterとsetter両方使うと思うので、@Dataに修正しました。

2022-11-01 15:33 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        form.setId(id);
@yoshi-koyama @YudaiNoda3576 
小山さんの言う通り、教材の通りに作りました。
updateForm と createFormに分ける必要はない認識で、
共通のformにまとめる方がいいと思っています。

2022-11-01 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    private int id;
@YudaiNoda3576 
はい、クライアントサイドから渡ってくることを想定しています。
PathVariableが使われるとクライアントが入力する情報ではないというのが分からないのです。
Update処理で指定するidが数字以外で入力されないようにバリデーションしています。

2022-11-01 15:49 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
>      @Size(max = 19)
@YudaiNoda3576 
こちら、教材を確認したら、20文字以下の仕様だったので、修正しました。

2022-11-01 15:51 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        } catch (NotFoundException e) {
@yoshi-koyama 
ExceptionHandlerを使っての共通化はこれから実装します。
実装完了しましたら、また連絡します。

2022-11-01 16:12 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +import net.raisetech.SpringBootSample.form.CreateForm;
@yoshi-koyama 
`.gitignore`に追加して、
`git rm`コマンドでgit管理下から削除しました。

2022-11-01 16:15 UTC, Daisuke943 commented
@YudaiNoda3576 @yoshi-koyama 
レビューありがとうございます。
指摘対応しましたので、確認をお願いします。
実行結果のスクリーンショットはreadme.mdにまとめています。
https://github.com/Daisuke943/RaiseTech_Java_202207#readme

2022-11-02 00:40 UTC, yoshi-koyama commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        form.setId(id);
承知です。
一応、教材でわけたいとは登録と更新は別の業務処理であり、Formの共通化ができなくなる可能性が高いと考えたからです。

例）
登録処理では名前と生年月日どちらも必須だが、更新処理では名前か生年月日どちらかが必須

ただ、今回のアプリケーションの状態のままであればわたしも共通化で良いと思います 👍 
YAGNIともいいますしね 😅

2022-11-02 00:41 UTC, yoshi-koyama approved these changes
わたしのコメントは問題ないです :shipit:

2022-11-02 03:04 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    private int id;
> PathVariableが使われるとクライアントが入力する情報ではないというのが分からない

でしたら、パスパラメータとクエリパラメータの使い分けの基準って説明出来ますか？？

2022-11-02 16:38 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    private int id;
@YudaiNoda3576 
パスパラメータは特定のリソースを識別するための情報を入れる時に使い、
今回の場合はどのnameを更新するか指定するときに使います。

クエリパラメータは特定のリソースを操作し取得する際に必要な情報を入れる時に使い、
NameControllerのgetMoviesメソッドに使われているように、映画の公開年でフィルタする時
などに使います。

こちらのサイトを参考にしました。
https://qiita.com/kazuma___/items/c4a41cbbe127002791a4

2022-11-03 05:16 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    private int id;
@Daisuke943 
ありがとうございます！
調べて頂いた内容もそうですね！
付け加えると、
パスパラメータを使用する場合ですが、基本的にリソースをユニークに特定し、省略できない値がパスパラメータに含まれるものになりますね！
逆にクエリパラメータは省略することが出来る値です。
なので具体的にいうと、今回のようなidはパスパラメータになり、検索機能で入力したワードなどはクエリパラメータになります。

つまり、今回はidはユーザーが入力することは想定されないという事が言いたかったです！

2023-01-01 16:17 UTC, YudaiNoda3576 commented
![LGTM](https://image.lgtmoon.dev/192813)

2023-06-30 10:59 UTC, merged