第6回課題
Daisuke943/RaiseTech_Java_202207 pull request #6
Opened 2022-09-12 15:00 UTC by Daisuke943

第6回課題のSpringBootでHelloWorldを表示して、
自分で考えた変更を加えるをやってみました。

レビューをお願い出来ますでしょうか。

2022-09-13 10:50 UTC, Daisuke943 commented
画面にHello Worldを表示する実装の他に、
- 現在時刻の表示
- URLからリクエストパラメータで渡した値を画面に表示
を実装してみました。

実行結果は以下になります。
<img width="437" alt="スクリーンショット 2022-09-13 19 39 31" src="https://user-images.githubusercontent.com/47516167/189881313-b9576331-4323-4a63-a7a5-67da77768257.png">
<img width="541" alt="スクリーンショット 2022-09-13 19 40 28" src="https://user-images.githubusercontent.com/47516167/189881315-47b6b41e-792e-4431-9755-3e1268ffcd5a.png">
<img width="467" alt="スクリーンショット 2022-09-13 19 41 53" src="https://user-images.githubusercontent.com/47516167/189881316-b6dce6a2-cc63-4015-bffd-35ccadee4d6d.png">

2022-09-13 17:00 UTC, YudaiNoda3576 requested changes
コメントしています！
デフォルト引数を設定していないパターンの修正のほどよろしくお願いします！

2022-09-13 17:00 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +	public String japantest(@RequestParam(value = "name") String name) {
つまり、デフォルト値がなかった場合は例外処理が必要になるということですね〜
またはこのパラメータが省略可能であれば`required = false` みたいな設定もできます。
ただその場合`null`になると思うので別途処理が必要になります！

2022-09-14 20:13 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-09-14 20:13 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			name = "日本";
Stringの比較には`==`ではなく、`String#equals` を使うようにしてください〜
理由は等値比較と等価比較について調べていただくとわかるかと思うので、その理由も共有いただけると幸いです！

また、nameがnullの時にバックエンド側で値を差し込むのは何か違う気がします🤔
これは本来ならエラーになる処理をユーザーが行なったのに、それを握りつぶして無理やり処理を続行させていることに相当するように思います！
なので、ここでやるべきなのはnameの値がなかった場合はnameを入力してください的なメッセージをクライアントに返してやるのが妥当な気がしますがいかがでしょうか？？

2022-09-16 00:47 UTC, YudaiNoda3576 requested changes
コメントしています〜
あと、操作ミスだと思うんですが、スレッドがresolve conversation になっていたのでそこにチェックを入れるとどうなるかも調べていただくと今後役に立つかもです！

2022-09-16 00:47 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(Objects.equals(name,null)) {
`Object`クラスの`equals`メソッドと`String`クラスの`equals`メソッドが存在するのでそれらの違いを調べてみて、どちらを使うのが適切か考えてみてください！:smile:

2022-09-16 00:47 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください";
nullの場合の実行結果のスクショも共有いただけると助かります！

2022-09-17 14:29 UTC, YudaiNoda3576 requested changes
コメントしています〜

2022-09-17 14:29 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(StringUtils.isEmpty(name)) {
Stringクラスのequalsメソッドがあるのですが、それを使って欲しかったです！
その際にObjectクラスのequalsメソッドとの違いについても調べていただき共有してください！:pray:

2022-09-17 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(name == null) {
リクエストパラメータが設定されていない場合も対応出来るように修正しました。

2022-09-17 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください";
null判定をequalsメソッドを使って実装しました。

`name.equals(null)`だとnameがnullだった場合に`nullpointerexception`が発生してしまうので、
`Objects.equals(name,null)`というように実装しました。
nameの値はバックエンド側で設定せずにブラウザ側に設定してもらうようreturnで返しています。

等値比較と等価比較については、
等値比較はインスタンスのアドレスが同じかどうか、
等価比較はインスタンスの内容が同じかどうかを判断します。

Stringは参照型なので、等値比較だと内容が同じでも、アドレスが違うとfalseと判定されてしまうので、
アドレスが違ってもインスタンスの内容が同じかどうか判定してくれる等価比較で比較する必要があるという理解になりました。

つまり、等価比較で比較してくれるequalsメソッドでStringは比較する必要があるということです。

認識違いがありましたら、指摘頂けると嬉しいです。

2022-09-17 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください";
nullの場合の実行結果は以下になります。
<img width="467" alt="スクリーンショット 2022-09-17 0 05 08" src="https://user-images.githubusercontent.com/47516167/190670797-55bf32dc-6e83-493b-9284-d2b492643fd4.png">

2022-09-17 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(Objects.equals(name,null)) {
`Object`クラスの`equals`メソッドと`String`クラスの`equals`の違いとしては、
ざっくりですが、`Object`クラスの`equals`はオブジェクトを比較する、
`String`クラスの`equals`はStringクラスの文字列を比較する、
という違いがあると思います。

ですので、この場合はStringクラスの`equals`を使いたいのですが、
null同士の判定に使うと`nullpointerexception`が発生してしまいます。

Stringクラスの`equals`を使って`nullpointerexception`を回避する方法があれば、
教えて頂けますでしょうか。

2022-09-17 15:48 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(StringUtils.isEmpty(name)) {
StringUtilsを使用してnull判定をしています。
この実装方法であれば、`nullpointerexception`は
発生しなく、空文字も判定出来るので、いかがでしょうか。

2022-09-17 15:49 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +		if(StringUtils.isEmpty(name)) {
こちらにもReplyしてみます。

ObjectクラスのequalsメソッドとStringクラスのequalsの違いとしては、
ざっくりですが、Objectクラスのequalsはオブジェクトを比較する、
StringクラスのequalsはStringクラスの文字列を比較する、
という違いがあると思います。

ですので、この場合はStringクラスのequalsを使いたいのですが、
null同士の判定に使うとnullpointerexceptionが発生してしまいます。

Stringクラスのequalsを使ってnullpointerexceptionを回避する方法があれば、
教えて頂けますでしょうか。

2022-09-17 15:51 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			name = "日本";
等値比較と等価比較については、
等値比較はインスタンスのアドレスが同じかどうか、
等価比較はインスタンスの内容が同じかどうかを判断します。

Stringは参照型なので、等値比較だと内容が同じでも、アドレスが違うとfalseと判定されてしまうので、
アドレスが違ってもインスタンスの内容が同じかどうか判定してくれる等価比較で比較する必要があるという理解になりました。

つまり、等価比較で比較してくれるequalsメソッドでStringは比較する必要があるということです。

認識違いがありましたら、指摘頂けると嬉しいです。

2022-09-17 16:01 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください。";
Stringクラスのequalsメソッドを使用してnull判定を実装してみました。
しかし、この実装だと　nameがnullだった場合に`nullpointerexception`
が発生してしまうのですが、解決方法はありますでしょうか。

2022-09-18 04:52 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください。";
@Daisuke943 
すみません、こちら僕が勘違いしておりまして、nullチェックの際はequalsメソッドで比較するのは適切ではありませんでした 🙇🏻 
大変失礼しました。

単純な文字列比較の際は調べて頂いた内容で認識は正しく、`String#equals`を使用するようにしてください〜

また、nullチェックの際はDaisukeさんが実装していた`StrigUtils#isEmpty`を使用するのも有効な手段です
Java8以降から`Optional`というクラスが実装されており、こちらもよく使われる(こっちの方が主流)のでこちらについても調べて頂き余裕があれば書き換えてみてください〜

FYI
https://relearn-java.com/null-safe/

一旦Daisukeさんの調べて頂いた内容などで十分かと思いますので、nullチェックの部分だけ`StrigUtils#isEmpty`を使うか`Optional`を使うかで修正頂き、マージしてください！（Optionalの使い方が不安な場合は再度こちらのPRでレビューさせていただくのでSlackからメンションしていただければと思います！）

お疲れ様でした！

2022-09-18 04:52 UTC, YudaiNoda3576 commented
![LGTM](https://images.lgtmgen.org/1d0443d4-a10c-4040-b67d-330453824be8)

2022-09-18 04:53 UTC, YudaiNoda3576 approved these changes

2022-09-18 15:53 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/SpringBootSampleApplication.java
> +			return "リクエストパラメータに値を設定してください。";
@YudaiNoda3576 
Optionalクラスを使用してnull判定をしてみました。
動作確認も問題なかったので、これでマージします。
レビューありがとうございました！

2022-09-18 15:53 UTC, merged