第7回課題提出
Daisuke943/RaiseTech_Java_202207 pull request #7
Opened 2022-09-26 16:04 UTC by Daisuke943

第7回課題のHTTPメソッドのGET/POST/PATCH/DELETEのリクエストを扱えるControllerを実装しました。
オリジナルの仕様としましては、?name=sakaiのようなクエリ文字列を受け取れるようにしました。

以下にPostmanでの動作確認結果を添付しましたので、レビューをお願いします。

- GETリクエスト
<img width="811" alt="image" src="https://user-images.githubusercontent.com/47516167/192324557-7bae1a17-1cfd-4d46-aea6-90578112ebea.png">

- POSTリクエスト
<img width="811" alt="image" src="https://user-images.githubusercontent.com/47516167/192324945-9dc64f90-de37-4482-a757-ea53bafc6b72.png">

- PATCHリクエスト
<img width="812" alt="image" src="https://user-images.githubusercontent.com/47516167/192325083-b8f7e381-5c9a-42db-be5e-aac9670b7dcf.png">

- DELETEリクエスト
<img width="811" alt="image" src="https://user-images.githubusercontent.com/47516167/192325284-d963fe7a-9fd9-4b5f-85e4-e7f2d9769a58.png">

2022-09-27 08:06 UTC, YudaiNoda3576 requested changes
コメントしております〜！

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        Optional<String> namenull = Optional.ofNullable(name);
`namenull`は`nameNull`かと思います！
またこの変数名は適切ではないように思います🤔

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +            return ResponseEntity.ok(Map.of("message", "リクエストパラメータに値を設定してください"));
`required = false`を設定していますが、ここではパラメータが必須であるように見えるので実装が矛盾しているように見えます:eye:
また、パラメータが必須になるのはURLの設計上適切ではないため（パラメータはOptionalであるべき）、パラメータを設定するように要求するのではなく、nameにはデフォルト値が設定されているかつパラメータで指定されたnameの人物が存在しないメッセージが返却されるのが妥当かなと思うのですがいかがでしょうか？？

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
`"http://localhost:8080"`とハードコードしないように修正のほどお願いします🙏

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    @GetMapping("/names")
複数形になっているのGoodです！:+1:

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
> +    public void setName(String name) {
setterメソッドは使用されているでしょうか？？

2022-09-27 08:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    public void setName(String name) {
CreateFormと同様

2022-09-27 14:25 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
> +    public void setName(String name) {
setterメソッドは使用していないです。こちら、削除した方がいいでしょうか？

2022-09-27 14:25 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/form/UpdateForm.java
> +    public void setName(String name) {
CreateFormと同様です。

2022-09-27 14:26 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
ハードコードにならないように、変数に定義しました。

2022-09-27 14:28 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        Optional<String> namenull = Optional.ofNullable(name);
nameにはデフォルト値を設定しましたので、namenullは削除しました。

2022-09-27 14:36 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +            return ResponseEntity.ok(Map.of("message", "リクエストパラメータに値を設定してください"));
確かにパラメータを設定するように要求するのは、適切ではないと思うので、nameにはデフォルト値を設定して、nameの人物が存在しないメッセージが返却するように実装しました。

2022-09-29 03:02 UTC, YudaiNoda3576 reviewed
コメントしております！
ちなみにですが、nameのバリデーションについては別PRで対応する想定という認識であってますか？？

2022-09-29 03:02 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
> +    public void setName(String name) {
そうですね！
不要なメソッドは基本的に定義しないほうが良いです！（他の開発者が見たときに必要なメソッドだと思って使用する人が出てくるため）

また、ことsetterに関していうと、このオブジェクトのメンバ変数を書き換えるものなので、オブジェクトのカプセル化を崩す要因になります。
なのでsetterメソッドは必要な場合のみ定義するのが良いかと思います。
実装者が書き換えられない想定で作成したクラスが、不要なsetterメソッドのせいで他の開発者によって書き換えられると思わぬバグを生む要因にもなりますので。。。

2022-09-29 03:02 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
ここについてはまだハードコードされていますね！
（ハードコードが何かについても調べて頂き、それの何がいけないのかも共有ください！）
Javaコース受講生の大迫亜希さんのコードが参考になると思いますので覗いて見てください〜

FYI
https://github.com/akiosako/raisetech-subject10b

2022-09-29 15:07 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
ハードコードとは、ソースコードの中に固定値をそのまま書いているコードのことです。
今回の例でいうと`"http://localhost:8080"`がハードコードにあたります。
何故、それがいけないかと言うと、理由が2つあり、

1. パッと見た時に分かりにくい
2. 後から変更するのが大変

１は今回、URLなので見たらなにか分かりますが、
例えば消費税1.1などは、いきなり1.1という数字が書かれていても何か分かりません。

２はもし、ローカル環境以外でこのアプリケーションを動かす時に、
わざわざ、"http://localhost:8080"の部分を修正しないといけなく、
今回は１箇所の修正で済みますが、数が多くなると修正も大変になります。

認識違いがありましたら、指摘お願いします。

2022-09-29 15:11 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
では、具体的にどう修正したらいいのか、まだ分からないので、
亜希さんのコードを読み込んでみます。

2022-09-29 15:14 UTC, Daisuke943 commented
nameのバリデーションについては、このPRで対応してみます。
今日はもう時間がないので、明日実装してみます。

2022-09-30 00:18 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
おおむね認識に間違いはないかと思います！
補足すると、開発者によって、ハードコードされている箇所とされていない箇所の差分が存在した場合、それに気づけないと思わぬバグをうむ可能性もあるというところも念頭に置かれると良いかと思います！

2022-10-01 11:38 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
ハードコードしないように実装しました。
Controllerクラスにフィールドに定数として定義しました。

2022-10-01 11:44 UTC, Daisuke943 commented
nameのバリデーションを実装しました。
PostメソッドとPatchメソッドで、リクエストで受け取ったnameが空文字かNullだった場合に
ステータスコード400で返すようにしています。

以下がPostmanでの動作確認結果です。
<img width="857" alt="image" src="https://user-images.githubusercontent.com/47516167/193407884-10d809de-04e6-4704-98e0-7e33020103c4.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/47516167/193407892-58997ac1-6ad9-4745-b842-1dca963c08d8.png">

2022-10-01 11:47 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +        String urlStr = "http://localhost:8080";
setterは使用していないで、削除しました。

2022-10-02 01:46 UTC, YudaiNoda3576 requested changes
コメントしています〜

2022-10-02 01:46 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/form/CreateForm.java
> +    @NotBlank
課題の要件としては
`バリデーションについて調べてnameが空文字、null、20文字以上の場合はエラーとする`
だと思うので、20文字以上の場合のバリデーションの実装もお願いします！

2022-10-02 02:02 UTC, Daisuke943 commented
nameが20文字以上の場合のバリデーションを実装しました。

以下がPostmanでの動作確認結果です。
<img width="867" alt="image" src="https://user-images.githubusercontent.com/47516167/193434651-d516689d-f624-4c5e-97c4-403a89d2aef8.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/47516167/193434657-d5e1465b-dbcc-44c3-8896-0202b97a121d.png">

2022-10-02 02:03 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    private final String localUrl = "http://localhost:8080";
URLのハードコード回避はこちらの実装で問題なかったでしょうか？

2022-10-02 02:06 UTC, YudaiNoda3576 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    private final String localUrl = "http://localhost:8080";
あ、すみません。見落としていました！
まだハードコードされていますね。。。

2022-10-02 02:52 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    private String localUrl;
application.propertiesにURLを定義して、Valueアノテーションで値を注入しています。
これでハードコードは回避出来ていると思うのですが、どうでしょうか。

2022-10-02 02:53 UTC, Daisuke943 commented on src/main/java/net/raisetech/SpringBootSample/controller/NameController.java
> +    private String localUrl;
Postmanでの動作確認です。
レスポンスヘッダーにLocationとして、URLｇ
<img width="813" alt="image" src="https://user-images.githubusercontent.com/47516167/193435766-401c258b-6427-4c08-a055-da8f438d102f.png">

2022-10-02 11:42 UTC, merged